name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1
        with:
          node-version: 24
          cache: true
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: ./scripts/build.sh

      - name: Publish to npm
        run: vp pm publish --access public --provenance --no-git-checks
